[[messageArchive]]
= Announcement
:author: Andrzej Wójcik
:version: v2.0 October 2017. Reformatted for v8.0.0.

:toc:
:numbered:
:website: http://www.tigase.net

== Major changes
Tigase Message Archiving component has undergone a few major changes to our code and structure. To continue to use Tigase Message Archiving component, a few changes may be needed to be made to your systems. Please see them below:

=== Database schema changes
We decided to no longer use _in-code_ database upgrade to update database schema of Message Archiving component and rather provide separate schema files for every supported database.

Additionally we moved from _in-code_ generated SQL statements to stored procedures which are now part of provided database schema files.

To continue usage of new versions of Message Archiving component it is required to manually load new component database schema, see <<Preparation of database>> section for informations about that.

WARNING: Loading of new database schema is required to use new version of Message Archiving component.

== New features

=== Support for Message Archive Management protocol
Now Tigase Message Archiving component supports searching of archived message using http://xmpp.org/extensions/xep-0313.html:[XEP-0313: Message Archive Management] protocol.

For details on how to enable this feature look into <<Support for MAM>>

=== Support for using separate database for different domains
Since this version it is possible to use separate archived messages based on domains.
This allows you to configure component to store archived message for particular domain to different database.

For more informations please look into <<Using separate store for archived messages>>
